/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GridDisplayPanel.java
 *
 * Created on Mar 15, 2013, 1:45:41 AM
 */
package citalyser.ui.visualization.panels.regulardisplaypanel.contentsdisplaypanel;

import citalyser.ui.control.DisplayMaster;
import citalyser.ui.visualization.panels.regulardisplaypanel.contentsdisplaypanel.griddisplaypanel.GridEntityPanel;
import java.util.Vector;

/**
 *
 * @author Tanmay Patil
 */
public class GridDisplayPanel extends javax.swing.JPanel {

    /** Creates new form GridDisplayPanel */
    public GridDisplayPanel() {
        gridEntityPanels = new Vector<>();
        initComponents();
    }

    public void addGridEntityPanel(GridEntityPanel gridEntityPanel) {
        gridEntityPanel.setDisplayMaster(displayMaster);
        gridEntityPanels.add(gridEntityPanel);
        this.add(gridEntityPanel);
    }    

    public void setGridEntityPanels(Vector<GridEntityPanel> gridEntityPanels) {
        this.gridEntityPanels = gridEntityPanels;
    }

    public Vector<GridEntityPanel> getGridEntityPanels() {
        return gridEntityPanels;
    }

    public void setDisplayMaster(DisplayMaster displayMaster) {
        this.displayMaster = displayMaster;
        for (GridEntityPanel gridEntityPanel : gridEntityPanels) {
            gridEntityPanel.setDisplayMaster(displayMaster);
        }
    }

    public DisplayMaster getDisplayMaster() {
        return displayMaster;
    }
    
    private DisplayMaster displayMaster;
    private Vector<GridEntityPanel> gridEntityPanels;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
