package citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.modules.listdisplaypanel;

import citalyser.model.Paper;
import citalyser.ui.control.DisplayMaster;

/**
 *
 * @author abhishek
 */
public class PaperDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaperDetailsPanel
     */
    private DisplayMaster displayMaster;
    public PaperDetailsPanel() {
        initComponents();
        this.viewCitationsLbl.setVisible(false);
    }
    
    public void render(Paper p)
    {
        this.paperTitleLbl.setText(p.getTitle());
        //this.paperinfolbl.setText();
        this.paperAbstractLbl.setText(p.getAbstract());
        this.paperCitedByLbl.setText("Cited By : " + p.getNumCites());
        if(p.getNumCites() > 0)
        {
            this.viewCitationsLbl.setVisible(true);
        }
    }
    private void setDisplayMaster(DisplayMaster displayMaster)
    {
        this.displayMaster = displayMaster;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paperTitleLbl = new org.jdesktop.swingx.JXLabel();
        paperinfolbl = new org.jdesktop.swingx.JXLabel();
        paperAbstractLbl = new org.jdesktop.swingx.JXLabel();
        paperCitedByLbl = new org.jdesktop.swingx.JXLabel();
        viewCitationsLbl = new org.jdesktop.swingx.JXLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        paperTitleLbl.setForeground(new java.awt.Color(0, 0, 204));
        paperTitleLbl.setText("jXLabel1");
        paperTitleLbl.setFont(new java.awt.Font("DejaVu Sans", 0, 8)); // NOI18N
        paperTitleLbl.setLineWrap(true);

        paperinfolbl.setForeground(new java.awt.Color(51, 153, 0));
        paperinfolbl.setText("jXLabel1");
        paperinfolbl.setToolTipText("");
        paperinfolbl.setLineWrap(true);

        paperAbstractLbl.setText("jXLabel1");
        paperAbstractLbl.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        paperAbstractLbl.setLineWrap(true);

        paperCitedByLbl.setText("jXLabel1");
        paperCitedByLbl.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        paperCitedByLbl.setLineWrap(true);

        viewCitationsLbl.setText("View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paperAbstractLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paperinfolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paperTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paperCitedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                        .addComponent(viewCitationsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(paperTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(paperinfolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paperAbstractLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paperCitedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCitationsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel paperAbstractLbl;
    private org.jdesktop.swingx.JXLabel paperCitedByLbl;
    private org.jdesktop.swingx.JXLabel paperTitleLbl;
    private org.jdesktop.swingx.JXLabel paperinfolbl;
    private org.jdesktop.swingx.JXLabel viewCitationsLbl;
    // End of variables declaration//GEN-END:variables
}
