/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListDisplayPanel.java
 *
 * Created on Mar 17, 2013, 2:50:25 AM
 */
package citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.modules;

import citalyser.model.Paper;
import citalyser.ui.control.DisplayMaster;
import javax.swing.ListModel;

/**
 *
 * @author Tanmay Patil
 */
public class ListDisplayPanel extends javax.swing.JPanel {

    /** Creates new form ListDisplayPanel */
    public ListDisplayPanel() {
        initComponents();
    }

    public void setDisplayMaster(DisplayMaster displayMaster) {
        this.displayMaster = displayMaster;
    }

    public DisplayMaster getDisplayMaster() {
        return displayMaster;
    }
    
    private DisplayMaster displayMaster;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<Paper>();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Paper> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void setList(ListModel<Paper> listModel) {
        jList1.setModel(listModel);
        jList1.repaint();
    }
}
