/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExternalPanel.java
 *
 * Created on Mar 11, 2013, 10:54:35 PM
 */
package citalyser.ui.visualization.panels;

import citalyser.ui.control.DisplayMaster;
import citalyser.ui.visualization.panels.external.SettingsPanel;

/**
 *
 * @author Tanmay Patil
 */
public class ExternalPanel extends javax.swing.JPanel {

    /** Creates new form ExternalPanel */
    public ExternalPanel() {
        initComponents();
        settingsPanel = new SettingsPanel();
        this.setLayout(new java.awt.GridBagLayout());
        add(settingsPanel);
        setBackground(new java.awt.Color(0, 0, 0, 150));
    }
    
    public void setDisplayMaster(DisplayMaster displayMaster) {
        this.displayMaster = displayMaster;
        settingsPanel.setDisplayMaster(displayMaster);
    }

    public SettingsPanel getSettingsPanel() {
        return settingsPanel;
    }
            
    private DisplayMaster displayMaster;
    private SettingsPanel settingsPanel;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1349, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
