/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContentDisplayPanel.java
 *
 * Created on Mar 9, 2013, 3:20:35 AM
 */
package citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel;

import citalyser.model.query.QueryResult;
import citalyser.ui.control.DisplayMaster;
import citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.CentralContentDisplayPanel;
import citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.DetailsDisplayPanel;
import javax.swing.plaf.basic.BasicSplitPaneDivider;

/**
 *
 * @author Tanmay Patil
 */
public class ContentDisplayPanel extends javax.swing.JPanel {

    /** Creates new form ContentDisplayPanel */
    public ContentDisplayPanel() {
        initComponents();
    }
    
    public void setDisplayMaster(DisplayMaster displayMaster) {
        this.displayMaster = displayMaster;
        centralContentDisplayPanel.setDisplayMaster(displayMaster);
        detailsDisplayPanel.setDisplayMaster(displayMaster);
    }

    public CentralContentDisplayPanel getCentralContentDisplayPanel() {
        return centralContentDisplayPanel;
    }

    public DetailsDisplayPanel getDetailsDisplayPanel() {
        return detailsDisplayPanel;
    }

    public void displayDetailsDisplayPanel(boolean value) {
        this.detailsDisplayPanelVisible = value;
        if (value) {
            jSplitPane1.setDividerLocation(jSplitPane1.getWidth()/2);
        } else {
            jSplitPane1.setDividerLocation(jSplitPane1.getWidth() - 20);
        }
    }
            
    private DisplayMaster displayMaster;
    private boolean detailsDisplayPanelVisible = false;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        centralContentDisplayPanel = new citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.CentralContentDisplayPanel();
        detailsDisplayPanel = new citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.DetailsDisplayPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(806);
        jSplitPane1.setDividerSize(20);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jSplitPane1ComponentResized(evt);
            }
        });
        jSplitPane1.setLeftComponent(centralContentDisplayPanel);
        jSplitPane1.setRightComponent(detailsDisplayPanel);

        BasicSplitPaneDivider divider = (BasicSplitPaneDivider) jSplitPane1.getComponent(0);
        divider.setBackground(java.awt.Color.WHITE);
        divider.setBorder(null);
        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jSplitPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jSplitPane1ComponentResized
        if (!detailsDisplayPanelVisible) {
            jSplitPane1.setDividerLocation(jSplitPane1.getWidth() - 20);
        }
    }//GEN-LAST:event_jSplitPane1ComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.CentralContentDisplayPanel centralContentDisplayPanel;
    private citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.DetailsDisplayPanel detailsDisplayPanel;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    public void flipToGridDisplayPanel() {
        ((java.awt.CardLayout) this.getLayout()).last(this);
    }

    public void flipToTableDisplayPanel() {
        ((java.awt.CardLayout) this.getLayout()).first(this);
    }

    public void clearAll() {
        centralContentDisplayPanel.clearAll();
        detailsDisplayPanel.clearAll();
    }
}
