/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContentDisplayPanel.java
 *
 * Created on Mar 9, 2013, 3:20:35 AM
 */
package citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel;

import citalyser.queryresult.QueryResult;
import citalyser.ui.control.DisplayMaster;
import citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.modules.GridDisplayPanel;
import citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.modules.TableDisplayPanel;

/**
 *
 * @author Tanmay Patil
 */
public class ContentDisplayPanel extends javax.swing.JPanel {

    /** Creates new form ContentDisplayPanel */
    public ContentDisplayPanel() {
        initComponents();
    }
    
    public void setDisplayMaster(DisplayMaster displayMaster) {
        this.displayMaster = displayMaster;
    }
    
    public void showResults(QueryResult queryResult) {
        
    }
            
    private DisplayMaster displayMaster;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void flipToGridDisplayPanel() {
        ((java.awt.CardLayout) this.getLayout()).last(this);
    }
}
