/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphViewPanel.java
 *
 * Created on Mar 17, 2013, 2:44:53 AM
 */
package citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel;

import citalyser.graph.CreateGraph;
import citalyser.graph.GraphHistory;
import citalyser.model.Paper;
import citalyser.ui.control.DisplayMaster;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Tanmay Patil
 */
public class GraphViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form GraphViewPanel
     */
    public GraphViewPanel() {
        initComponents();
        graphHistory = new GraphHistory();
        jButton1.setVisible(false);
        jButton2.setVisible(false);
    }

    public void setDisplayMaster(DisplayMaster displayMaster) {
        this.displayMaster = displayMaster;
    }

    public GraphHistory getGraphHistory() {
        return graphHistory;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setPaper(Paper paper) {
        cg = new CreateGraph(paper, this);
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(cg.getVisualizationViewer(), BorderLayout.CENTER);
        cg.getVisualizationViewer().setSize(new Dimension(jPanel1.getWidth(), jPanel1.getHeight()));

    }
    private DisplayMaster displayMaster;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Paper title");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(72, 34));
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Previous");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, java.awt.BorderLayout.WEST);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(220, 220, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Paperlist history");
        jLabel2.setOpaque(true);
        jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jButton2.setText("Next");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 20));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel4);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jSlider1.setForeground(new java.awt.Color(0, 0, 0));
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(20);
        jSlider1.setMinimum(1);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(10);
        jPanel7.add(jSlider1);

        jPanel6.add(jPanel7, java.awt.BorderLayout.LINE_START);

        add(jPanel6, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!graphHistory.isCurrentPositionFirst()) {
            cg.populateOnPrevNext(graphHistory.gotoPreviousnodeInfo());
            cg.layouttop.setGraph(cg.sgv.g2);
            cg.vv.repaint();
            jButton2.setVisible(true);
            if (graphHistory.isCurrentPositionFirst()) {
                jButton1.setVisible(false);
            }
        }

        if (graphHistory.isCurrentPositionFirst()) {
            jButton1.setVisible(false);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!graphHistory.isCurrentPositionLast()) {
            cg.populateOnPrevNext(graphHistory.gotoNextnodeInfo());
            cg.layouttop.setGraph(cg.sgv.g2);
            cg.vv.repaint();
            jButton1.setVisible(true);
            if (graphHistory.isCurrentPositionLast()) {
                jButton2.setVisible(false);
            }
        }

        if (graphHistory.isCurrentPositionLast()) {
            jButton2.setVisible(false);
        }    }//GEN-LAST:event_jButton2ActionPerformed
    private GraphHistory graphHistory;
    private CreateGraph cg;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
