/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphViewPanel.java
 *
 * Created on Mar 17, 2013, 2:44:53 AM
 */
package citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel;

import citalyser.graph.CreateGraph;
import citalyser.model.Paper;
import citalyser.ui.control.DisplayMaster;
import java.awt.BorderLayout;

/**
 *
 * @author Tanmay Patil
 */
public class GraphViewPanel extends javax.swing.JPanel {

    /** Creates new form GraphViewPanel */
    public GraphViewPanel() {
        initComponents();
    }

    public void setDisplayMaster(DisplayMaster displayMaster) {
        this.displayMaster = displayMaster;
    }
    public void setPaper(Paper paper) {
        CreateGraph cg = new CreateGraph(paper);
        this.setLayout(new BorderLayout());
        add(cg.getVisualizationViewer());
        
    }

    
    private DisplayMaster displayMaster;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
