/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Mar 9, 2013, 3:09:44 AM
 */
package citalyser.ui.visualization;

import citalyser.ui.control.DisplayMaster;
import citalyser.ui.visualization.panels.RegularDisplayPanel;
import citalyser.ui.visualization.panels.StartPanel;

/**
 *
 * @author Tanmay Patil
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/citalyser/ui/visualization/resources/logo.png")).getImage());
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    public void setDisplayMaster(DisplayMaster displayMaster) {
        this.displayMaster = displayMaster;
        startPanel.setDisplayMaster(displayMaster);
        regularDisplayPanel.setDisplayMaster(displayMaster);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel = new citalyser.ui.visualization.panels.StartPanel();
        regularDisplayPanel = new citalyser.ui.visualization.panels.RegularDisplayPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Citalyser 1.0");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(startPanel, "card3");
        getContentPane().add(regularDisplayPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        try {
            displayMaster.mainFrameChanged(getX() + getRootPane().getX(), getY() + getRootPane().getY(), getContentPane().getWidth(), getContentPane().getHeight());
        } catch(NullPointerException ex) {
            
        }
    }//GEN-LAST:event_formWindowStateChanged

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        try {
            displayMaster.mainFrameChanged(getX() + getRootPane().getX(), getY() + getRootPane().getY(), getContentPane().getWidth(), getContentPane().getHeight());
        } catch(NullPointerException ex) {
            
        }
    }//GEN-LAST:event_formComponentMoved

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        try {
            displayMaster.mainFrameChanged(getX() + getRootPane().getX(), getY() + getRootPane().getY(), getContentPane().getWidth(), getContentPane().getHeight());
        } catch(NullPointerException ex) {
            
        }
    }//GEN-LAST:event_formComponentResized

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            displayMaster.mainFrameChanged(getX() + getRootPane().getX(), getY() + getRootPane().getY(), getContentPane().getWidth(), getContentPane().getHeight());
        } catch(NullPointerException ex) {
            
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            displayMaster.mainFrameChanged(getX() + getRootPane().getX(), getY() + getRootPane().getY(), getContentPane().getWidth(), getContentPane().getHeight());
        } catch(NullPointerException ex) {
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            displayMaster.mainFrameChanged(getX() + getRootPane().getX(), getY() + getRootPane().getY(), getContentPane().getWidth(), getContentPane().getHeight());
        } catch(NullPointerException ex) {
            
        }
    }//GEN-LAST:event_formWindowGainedFocus

    static {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    public RegularDisplayPanel getRegularDisplayPanel() {
        return regularDisplayPanel;
    }

    public StartPanel getStartPanel() {
        return startPanel;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    private DisplayMaster displayMaster;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private citalyser.ui.visualization.panels.RegularDisplayPanel regularDisplayPanel;
    private citalyser.ui.visualization.panels.StartPanel startPanel;
    // End of variables declaration//GEN-END:variables
}
