/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataVisualizationPanel.java
 *
 * Created on Mar 17, 2013, 2:44:17 AM
 */
package citalyser.ui.visualization.panels.regulardisplaypanel;

/**
 *
 * @author Tanmay Patil
 */
public class DataVisualizationPanel extends javax.swing.JPanel {

    /** Creates new form DataVisualizationPanel */
    public DataVisualizationPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentDisplayPanel = new citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.ContentDisplayPanel();
        graphViewPanel = new citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.GraphViewPanel();

        setLayout(new java.awt.CardLayout());
        add(contentDisplayPanel, "card3");

        javax.swing.GroupLayout graphViewPanelLayout = new javax.swing.GroupLayout(graphViewPanel);
        graphViewPanel.setLayout(graphViewPanelLayout);
        graphViewPanelLayout.setHorizontalGroup(
            graphViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        graphViewPanelLayout.setVerticalGroup(
            graphViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );

        add(graphViewPanel, "card3");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.ContentDisplayPanel contentDisplayPanel;
    private citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.GraphViewPanel graphViewPanel;
    // End of variables declaration//GEN-END:variables
}
