/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatusDisplayPanel.java
 *
 * Created on Mar 17, 2013, 3:12:45 AM
 */
package citalyser.ui.visualization.panels.regulardisplaypanel;

/**
 *
 * @author Tanmay Patil
 */
public class StatusDisplayPanel extends javax.swing.JPanel {

    /** Creates new form StatusDisplayPanel */
    public StatusDisplayPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
