/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DetailsDisplayPanel.java
 *
 * Created on Mar 9, 2013, 4:22:42 PM
 */
package citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel;

import citalyser.ui.control.DisplayMaster;
import citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.detailsdisplaypanel.LowerDetailsDisplayPanel;
import citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.detailsdisplaypanel.UpperDetailsDisplayPanel;
import javax.swing.JButton;

/**
 *
 * @author Tanmay Patil
 */
public class DetailsDisplayPanel extends javax.swing.JPanel {
private String name="Author";

    public void setNameJounal(boolean isJourn){
        if(isJourn){
            name="Journal";
        }
        else{
            name="Author";
        }
    }
    public void clearAll() {
        upperDetailsDisplayPanel.clearAll();
        lowerDetailsDisplayPanel.clearAll();
    }
    
    private class PainterThread extends Thread {
        
        private int dividerLocation;

        public PainterThread(int dividerLocation) {
            this.dividerLocation = dividerLocation;
        }

        @Override
        public void run() {
            jSplitPane1.setDividerLocation(dividerLocation);
        }
        
    }

    /** Creates new form DetailsDisplayPanel */
    public DetailsDisplayPanel() {
        initComponents();
    }
    
    public void setDisplayMaster(DisplayMaster displayMaster) {
        this.displayMaster = displayMaster;
        upperDetailsDisplayPanel.setDisplayMaster(displayMaster);
        lowerDetailsDisplayPanel.setDisplayMaster(displayMaster);
    }

    public UpperDetailsDisplayPanel getUpperDetailsDisplayPanel() {
        return upperDetailsDisplayPanel;
    }

    public LowerDetailsDisplayPanel getLowerDetailsDisplayPanel() {
        return lowerDetailsDisplayPanel;
    }

    public void flipToUpperDetailsDisplayPanel() {
        if (!upperVisible && !animating) {
            upperVisible = true;
            final JButton myButton = jButton1;
            new Thread() {

                @Override
                public void run() {
                    PainterThread painterThread = new PainterThread(0);
                    
                    myButton.setText("Displaying "+name+" Profile");
                    int target = lowerAvailable ? jSplitPane1.getHeight() - 24 : jSplitPane1.getHeight();
                    animating = true;
                    for (int i = 0; i < target; i++) {
                        if (!painterThread.isAlive()) {
                            painterThread = new PainterThread(i);
                            painterThread.start();
                        }
                        try {
                            Thread.sleep(1);
                        } catch (InterruptedException ex) {
                            ex.printStackTrace();
                        }
                    }
                    animating = false;
                    myButton.setText("Display Citations List");
                }
            }.start();
        }
    }

    public void flipToLowerDetailsDisplayPanel() {
        lowerAvailable = true;
        if (upperVisible && !animating) {
            upperVisible = false;
            final JButton myButton = jButton1;
            new Thread() {

                @Override
                public void run() {
                    PainterThread painterThread = new PainterThread(0);
                    
                    myButton.setText("Displaying Citations List");
                    animating = true;
                    for (int i = jSplitPane1.getHeight(); i > 0; i--) {
                        if (!painterThread.isAlive()) {
                            painterThread = new PainterThread(i);
                            painterThread.start();
                        }
                        try {
                           Thread.sleep(1);
                        } catch (InterruptedException ex) {
                            ex.printStackTrace();
                        }
                    }
                    animating = false;
                    myButton.setText("Display "+name+" Profile");
                }
            }.start();
        }
    }

    public void setLowerAvailable(boolean lowerAvailable) {
        this.lowerAvailable = lowerAvailable;
    }
            
    private DisplayMaster displayMaster;
    private boolean upperVisible = true;
    private boolean animating = false;
    private boolean lowerAvailable = false;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        upperDetailsDisplayPanel = new citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.detailsdisplaypanel.UpperDetailsDisplayPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lowerDetailsDisplayPanel = new citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.detailsdisplaypanel.LowerDetailsDisplayPanel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 153, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(0);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setTopComponent(upperDetailsDisplayPanel);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Show Author Profile");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.PAGE_START);
        jPanel1.add(lowerDetailsDisplayPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 5));
        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setRightComponent(jPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if (upperVisible) {
            if (lowerAvailable) {
                jSplitPane1.setDividerLocation(jSplitPane1.getHeight() - 24);
            } else {
                jSplitPane1.setDividerLocation(jSplitPane1.getHeight());
            }
        }
    }//GEN-LAST:event_formComponentResized

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (upperVisible) {
            flipToLowerDetailsDisplayPanel();
        } else {
            flipToUpperDetailsDisplayPanel();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.detailsdisplaypanel.LowerDetailsDisplayPanel lowerDetailsDisplayPanel;
    private citalyser.ui.visualization.panels.regulardisplaypanel.datavisualizationpanel.contentdisplaypanel.detailsdisplaypanel.UpperDetailsDisplayPanel upperDetailsDisplayPanel;
    // End of variables declaration//GEN-END:variables
}
